In [2]:
import torch

In [8]:
x = torch.tensor([[1,2,3,4,5],[6,7,8,9,0]])
print(x)

tensor([[1, 2, 3, 4, 5],
        [6, 7, 8, 9, 0]])


In [9]:
x = torch.randint(0,10,[3,3])
print(x)

tensor([[6, 1, 6],
        [0, 4, 1],
        [8, 2, 9]])


In [10]:
y = torch.randint(0,10,(3,3))
print(y)

tensor([[3, 5, 6],
        [4, 6, 2],
        [3, 0, 0]])


In [11]:
c = x @ y
print(c)

tensor([[40, 36, 38],
        [19, 24,  8],
        [59, 52, 52]])


In [3]:
a = torch.tensor(5.0 , requires_grad = True)
b = torch.tensor(8.0 , requires_grad = True)
ab = a * b
print(ab)
ab.backward()
print('Gradient of a:',float(a.grad))
print('Gradient of b:',float(b.grad))

tensor(40., grad_fn=<MulBackward0>)
Gradient of a: 8.0
Gradient of b: 5.0


In [1]:
print('Pytorch')

Pytorch


Autograd

In [5]:
w = torch.tensor(5.0, requires_grad = True)
b = torch.tensor(8.0, requires_grad = True)
optimiser = torch.optim.SGD([w,b], lr = 0.01)

marks = torch.tensor([10,30,40,60,80])
hours = torch.tensor([0.50, 1,1.5,2,3])

for epochs in range(100):
    optimiser.zero_grad()
    y_cap = w * hours + b

    loss = ((y_cap - marks) ** 2).mean()
    loss.backward()
    optimiser.step()

print('Weight is: ',w.item())
print('Bias is: ',b.item())


Weight is:  22.09794044494629
Bias is:  10.6470947265625


nn.module

In [ ]:
import torch.nn as nn
x = torch.randint(0,30,[4,4]).float()
y = torch.randint(0,30,[4,4]).float()

class LinearModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.layer = nn.Linear(4,4) #(1,1) means one input and one output
    def forward(self, x):
        return self.layer(x)

model = LinearModel()
loss_function = nn.MSELoss() #Calculates loss ((y_cap - y)**2).mean()
optimiser = torch.optim.SGD(model.parameters(), lr = 0.0001)

for epoch in range(1000):
    y_cap = model(x) #y_cap = w * x + b and it also calls forward function.
    loss = loss_function(y_cap, y) #Calculates loss ((prediction - actual_value)**2).mean()
    optimiser.zero_grad() #Set the previous gradient to zero.
    loss.backward() #It calculates gradients/derivatives
    optimiser.step() #Updates parameters (weights and bias) using the formula (w_new = w_old - learning_rate * gradient)

print("Weight: ",model.layer.weight)
print("Bias: ",model.layer.bias)

Weight:  Parameter containing:
tensor([[ 0.1517,  0.6287, -0.3469,  0.6986],
        [ 0.4033, -0.1821,  0.3366,  0.4170],
        [ 0.9610,  0.2438,  0.6667,  0.2002],
        [ 0.1922,  0.1026,  0.5312,  0.1682]], requires_grad=True)
Bias:  Parameter containing:
tensor([-0.0626, -0.0831, -0.1472,  0.5402], requires_grad=True)
