In [1]:
import torch

In [8]:
x = torch.tensor([[1,2,3,4,5],[6,7,8,9,0]])
print(x)

tensor([[1, 2, 3, 4, 5],
        [6, 7, 8, 9, 0]])


In [9]:
x = torch.randint(0,10,[3,3])
print(x)

tensor([[6, 1, 6],
        [0, 4, 1],
        [8, 2, 9]])


In [10]:
y = torch.randint(0,10,(3,3))
print(y)

tensor([[3, 5, 6],
        [4, 6, 2],
        [3, 0, 0]])


In [11]:
c = x @ y
print(c)

tensor([[40, 36, 38],
        [19, 24,  8],
        [59, 52, 52]])


In [3]:
a = torch.tensor(5.0 , requires_grad = True)
b = torch.tensor(8.0 , requires_grad = True)
ab = a * b
print(ab)
ab.backward()
print('Gradient of a:',float(a.grad))
print('Gradient of b:',float(b.grad))

tensor(40., grad_fn=<MulBackward0>)
Gradient of a: 8.0
Gradient of b: 5.0


In [1]:
print('Pytorch')

Pytorch


In [5]:
marks = torch.tensor([20,30,50,70,95])
hours = torch.tensor([1,1.5,2,3,4])

w = torch.tensor(3.0, requires_grad = True)
b = torch.tensor(8.0, requires_grad = True)
optimiser = torch.optim.SGD([w,b], lr = 0.01)
optimiser

SGD (
Parameter Group 0
    dampening: 0
    differentiable: False
    foreach: None
    fused: None
    lr: 0.01
    maximize: False
    momentum: 0
    nesterov: False
    weight_decay: 0
)